[
    "Abra", "Kadabra", "Alakazam",
    "Aerodactyl",
    "Articuno",
    "Bellsprout", "Weepinbell", "Victreebel",
    "Bulbasaur", "Ivysaur", "Venusaur",
    "Caterpie", "Metapod", "Butterfree",
    "Chansey",
    "Charmander", "Charmeleon", "Charizard",
    "Clefairy", "Clefable",
    "Cubone", "Marowak",
    "Diglett", "Dugtrio",
    "Ditto",
    "Doduo", "Dodrio",
    "Dratini", "Dragonair", "Dragonite",
    "Drowzee", "Hypno",
    "Electabuzz",
    "Ekans", "Arbok",
    "Eevee", "Vaporeon", "Jolteon", "Flareon",
    "Exeggcute", "Exeggutor",
    "Farfetchd",
    "Gastly", "Haunter", "Gengar",
    "Geodude", "Graveler", "Golem",
    "Goldeen", "Seaking",
    "Grimer", "Muk",
    "Growlithe", "Arcanine",
    "Hitmonlee",
    "Hitmonchan",
    "Horsea", "Seadra",
    "Jigglypuff", "Wigglytuff",
    "Jynx",
    "Kabuto", "Kabutops",
    "Kangaskhan",
    "Koffing", "Weezing",
    "Krabby", "Kingler",
    "Lapras",
    "Lickitung",
    "Machop", "Machoke", "Machamp",
    "Magikarp", "Gyarados",
    "Magmar",
    "Magnemite", "Magneton",
    "Mankey", "Primeape",
    "Meowth", "Persian",
    "Mew", "Mewtwo",
    "Mrmime",
    "Moltres",
    "NidoranMale", "Nidorino", "Nidoking",
    "NidoranFemale", "Nidorina", "Nidoqueen",
    "Oddish", "Gloom", "Vileplume",
    "Omanyte", "Omastar",
    "Onix",
    "Paras", "Parasect",
    "Pidgey", "Pidgeotto", "Pidgeot",
    "Pinsir",
    "Pikachu", "Raichu",
    "Poliwag", "Poliwhirl", "Poliwrath",
    "Ponyta", "Rapidash",
    "Porygon",
    "Psyduck", "Golduck",
    "Rattata", "Raticate",
    "Rhyhorn", "Rhydon",
    "Sandshrew", "Sandslash",
    "Seel", "Dewgong",
    "Shellder", "Cloyster",
    "Scyther",
    "Slowpoke", "Slowbro",
    "Snorlax",
    "Spearow", "Fearow",
    "Staryu", "Starmie",
    "Squirtle", "Wartortle", "Blastoise",
    "Tangela",
    "Tauros",
    "Tentacool", "Tentacruel",
    "Venonat", "Venomoth",
    "Voltorb", "Electrode",
    "Vulpix", "Ninetales",
    "Weedle", "Kakuna", "Beedrill",
    "Zapdos",
    "Zubat", "Golbat"]